from __future__ import annotations

from types import MappingProxyType
from typing import Final, Mapping


CSV_COLUMNS: Final[Mapping[str, str]] = MappingProxyType(
    {
        "gbifID": "BIGINT",
        "datasetKey": "VARCHAR",
        "occurrenceID": "VARCHAR",
        "kingdom": "VARCHAR",
        "phylum": "VARCHAR",
        "class": "VARCHAR",
        "order": "VARCHAR",
        "family": "VARCHAR",
        "genus": "VARCHAR",
        "species": "VARCHAR",
        "infraspecificEpithet": "VARCHAR",
        "taxonRank": "VARCHAR",
        "scientificName": "VARCHAR",
        "verbatimScientificName": "VARCHAR",
        "verbatimScientificNameAuthorship": "VARCHAR",
        "countryCode": "VARCHAR",
        "locality": "VARCHAR",
        "stateProvince": "VARCHAR",
        "occurrenceStatus": "VARCHAR",
        "individualCount": "BIGINT",
        "publishingOrgKey": "VARCHAR",
        "decimalLatitude": "DOUBLE",
        "decimalLongitude": "DOUBLE",
        "coordinateUncertaintyInMeters": "DOUBLE",
        "coordinatePrecision": "DOUBLE",
        "elevation": "DOUBLE",
        "elevationAccuracy": "DOUBLE",
        "depth": "DOUBLE",
        "depthAccuracy": "DOUBLE",
        "eventDate": "VARCHAR",
        "day": "BIGINT",
        "month": "BIGINT",
        "year": "BIGINT",
        "taxonKey": "BIGINT",
        "speciesKey": "BIGINT",
        "basisOfRecord": "VARCHAR",
        "institutionCode": "VARCHAR",
        "collectionCode": "VARCHAR",
        "catalogNumber": "VARCHAR",
        "recordNumber": "VARCHAR",
        "identifiedBy": "VARCHAR",
        "dateIdentified": "VARCHAR",
        "license": "VARCHAR",
        "rightsHolder": "VARCHAR",
        "recordedBy": "VARCHAR",
        "typeStatus": "VARCHAR",
        "establishmentMeans": "VARCHAR",
        "lastInterpreted": "VARCHAR",
        "mediaType": "VARCHAR",
        "issue": "VARCHAR",
    }
)
